version: "3.8"
services:
  web:
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app
    restart: always

  nginx:
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./services/website/static:/static:rw
      - ./.log/nginx:/var/log/nginx
      - ./.certificates/nginx:/etc/letsencrypt/live/robertreaney.com:rw
      # - ./.certificates/certbot/www/:/var/www/certbot/:ro
      # - ./.certificates/certbot/conf/:/etc/letsencrypt/:rw
    restart: always

  # certbot:
  #   container_name: certbot-server
  #   image: certbot/certbot:latest
  #   volumes: 
  #     - ./.log/certbot/www/:/var/www/certbot/:rw
  #     - ./.log/certbot/conf/:/etc/letsencrypt/:rw
  #   restart: always