# This is a basic workflow to help you get started with Actions

name: CI
run-name: ${{ github.actor }} is testing out cicd on github

# Controls when the workflow will run
on: [push]
# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
#   workflow_dispatch:

jobs:
  deploy-website:
    name: Deploy Website to s3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Deps
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.16'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: AWS Credentials
        uses: aaws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: {{ secrets.AWS_ROLE_ARN }}
          role-session-name: githubActions
          aws-region: us-east-1
      - name: Update s3
        run: python pipeline.py