# This is a basic workflow to help you get started with Actions

name: CI
run-name: ${{ github.actor }} is testing out cicd on github

# Controls when the workflow will run
on: [push]
# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
#   workflow_dispatch:

jobs:
  deploy-website:
    name: Deploy Website to s3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.16'
      - run: pip install -r requirements.txt
      - run: python pipeline.py